### PR TITLE
Correctly configure the Loggers to actually display something

### PR DESCRIPTION
**Pull request by thebillkidy**
When testing the usage.md and writing a deep-dive about it, I noticed that the logs are not actually showing something. Diving deeper into this, it seems no default handler is configured so python defaults to the WARNING level rather than the INFO level. 

Adding these commits will start to actually display something.

### CODE REVIEW

**Comment by MisterTea** [comment]
@thebillkidy Friendly ping :-)

**Comment by thebillkidy** [comment]
Heya! Sorry, was kinda crowded at work past days :) will work on this right away!

**Comment by thebillkidy** [comment]
As requested @MisterTea ;) p.s. in the meantime I took the time to write an article about it, feel free to check + give comments about it! https://xaviergeerinck.com/facebook-horizon

**Comment by MisterTea** [comment]
Hey @thebillkidy !  Can you please sign the CLA so we can merge your changes?  Thanks!!  https://code.facebook.com/cla

**Comment by thebillkidy** [comment]
Done :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MisterTea** [comment]
Cool.  There's some issue with your PR because it has 37 commits.  Maybe you need to rebase onto master?  Once the PR is limited to your changes, I can merge.  Thanks!

**Comment by thebillkidy** [comment]
> 
> 
> Cool. There's some issue with your PR because it has 37 commits. Maybe you need to rebase onto master? Once the PR is limited to your changes, I can merge. Thanks!

Hi, rebased onto master :)

**Pull request closed without merging**
