### PR TITLE
Update installation & usage guide, and fix issues related to that.

### PR DESCRIPTION
**Pull request by MisterTea**

### CODE REVIEW

**Comment by baek-jinoo** [comment]
Might want to update `<spark.version>2.3.1</spark.version>` in `preprocessing/pom.xml`

**Comment by baek-jinoo** [comment]
Also, adding `-v ~/.m2:/root/.m2` in `docker run -v $PWD/../:/home/Horizon -p 0.0.0.0:6006:6006 -it horizon:dev` to make `docker run -v ~/.m2:/root/.m2 -v $PWD/../:/home/Horizon -p 0.0.0.0:6006:6006 -it horizon:dev` helps with the building process again.

Also, seems like if we run `mvn -f preprocessing/pom.xml clean package` twice in a row, the subsequent run fails due to dirty directory. Something is leftover to make the test fail.

**Comment by MisterTea** [comment]
@baek-jinoo Great feedback!  Updated with your feedback

**Comment by baek-jinoo** [comment]
My bad, might want to do `$HOME/.m2` instead of `~/.m2` to be consistent with `$PWD`

**Pull request closed without merging**
