### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by baek-jinoo**
Update spark to match pom.xml and doc.

### CODE REVIEW

**Comment by baek-jinoo** [comment]
I think there are tests failing in master already...

**Comment by MisterTea** [comment]
Hey @baek-jinoo I'm sure your diff is fine but our internal tool for merging PRs is flaking out so I'm going to make a new commit.

**Comment by baek-jinoo** [comment]
Go for it.

**Comment by MisterTea** [comment]
Thanks for fixing this!

**Pull request closed without merging**
